image: Visual Studio 2017
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
branches:
  only:
    - l10n_master # The branch that Crowdin targets when updates are made on .po files
    - dev         # The branch that gets deployed to MyGet
    - master      # The branch that is published on Nuget.org
init:
  - git config --global core.autocrlf true
install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
build_script:
  - dotnet --version
artifacts:
  - path: 'artifacts\**\*.nupkg'
deploy:
  - provider: NuGet
    on:
      branch: master
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: ufjIZJ6RigWF9emw//cBuu/OE63BUWWEcspLrfYkRLJdjSEAgqZYcF17pYYW3We7
    skip_symbols: true
    artifact: /.*\.nupkg/
  - provider: NuGet
    on:
      branch: dev
    server: https://www.myget.org/F/orchardcore-preview/api/v2/package
    api_key:
      secure: zFOa19bQQsM/YV7mrHwGdElRhCGSRq3CqZ7xACS0iEPRJk8mdNgSrjPjnMR1LOGo
    skip_symbols: true
    artifact: /.*\.nupkg/
