image: Visual Studio 2017
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
branches:
  only:
    - dev         # The branch that gets deployed to MyGet
    - master      # The branch that is published on Nuget.org
environment:
  packageVersion: 1.0.0
  versionPrefix: -beta3
init:
  - git config --global core.autocrlf true
  - ps: $env:nugetVersion = "$env:packageVersion$env:versionPrefix.$env:appveyor_build_number"
install:
  - ps: Start-FileDownload 'https://dist.nuget.org/win-x86-commandline/latest/nuget.exe'
build_script:
  - dotnet --version
  - ps: .\pack.ps1
artifacts:
  - path: 'artifacts\**\*.nupkg'
deploy:
  - provider: NuGet
    on:
      branch: master
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: ufjIZJ6RigWF9emw//cBuu/OE63BUWWEcspLrfYkRLJdjSEAgqZYcF17pYYW3We7
    skip_symbols: true
    artifact: /.*\.nupkg/
  - provider: NuGet
    on:
      branch: dev
    server: https://www.myget.org/F/orchardcore-preview/api/v2/package
    api_key:
      secure: zFOa19bQQsM/YV7mrHwGdElRhCGSRq3CqZ7xACS0iEPRJk8mdNgSrjPjnMR1LOGo
    skip_symbols: true
    artifact: /.*\.nupkg/
  - provider: NuGet
    on:
      branch: dev
    server: https://www.myget.org/F/orchardcore-dev/api/v2/package
    api_key:
      secure: zFOa19bQQsM/YV7mrHwGdElRhCGSRq3CqZ7xACS0iEPRJk8mdNgSrjPjnMR1LOGo
    skip_symbols: true
    artifact: /.*\.nupkg/
